#!/usr/bin/env python3
"""播种 50 道中国家常菜谱到 recipes 表。

用法：
    cd backend
    python -m scripts.seed_recipes

要求：DATABASE_URL 在 .env 中配置。
"""

from __future__ import annotations

import asyncio
import logging
import os
import sys
import uuid

# 确保 backend/ 在 sys.path 中，让 "python -m scripts.seed_recipes" 可用
_THIS_DIR = os.path.dirname(os.path.abspath(__file__))
_BACKEND_DIR = os.path.dirname(_THIS_DIR)
if _BACKEND_DIR not in sys.path:
    sys.path.insert(0, _BACKEND_DIR)

from sqlalchemy import select

from app.config import settings
from app.database import async_session
from app.models.recipe import Recipe

logging.basicConfig(level=logging.INFO, format="%(asctime)s  %(message)s")
logger = logging.getLogger("seed_recipes")

# ═══════════════════════════════════════════════════════════════════
# 50 道菜谱数据
# ═══════════════════════════════════════════════════════════════════

RECIPES: list[dict] = [
    # ── 早餐 (10) ──────────────────────────────────────────────
    {
        "name": "小米南瓜粥",
        "category": "chinese",
        "meal_type": "breakfast",
        "cooking_method": "boil",
        "prep_time_min": 10,
        "cook_time_min": 30,
        "difficulty": "easy",
        "ingredients": [
            {"name": "小米", "amount_g": 60},
            {"name": "南瓜", "amount_g": 150},
            {"name": "水", "amount_g": 800},
        ],
        "steps": [
            "小米淘洗两遍，清水浸泡 15 分钟。",
            "南瓜去皮去瓤，切成 2cm 见方的小丁。",
            "锅中加 800ml 水烧开，放入小米，大火煮 5 分钟后转小火。",
            "加入南瓜丁，小火熬煮 20 分钟至粥稠南瓜软烂。",
            "期间搅拌 2-3 次防止粘锅。出锅即可食用。",
        ],
        "nutrition_per_serving": {"calories": 210, "protein_g": 5.5, "fat_g": 2.0, "carbs_g": 42.0},
        "serving_size": "1碗（约350g）",
        "tags": ["low_fat", "easy_digest", "vegetarian"],
        "suitable_goal": "all",
    },
    {
        "name": "皮蛋瘦肉粥",
        "category": "chinese",
        "meal_type": "breakfast",
        "cooking_method": "boil",
        "prep_time_min": 15,
        "cook_time_min": 40,
        "difficulty": "medium",
        "ingredients": [
            {"name": "大米", "amount_g": 80},
            {"name": "猪瘦肉", "amount_g": 60},
            {"name": "皮蛋", "amount_g": 50},
            {"name": "生姜", "amount_g": 5},
            {"name": "水", "amount_g": 1000},
        ],
        "steps": [
            "大米淘洗后加少许油和盐腌制 15 分钟。",
            "猪瘦肉切细丝，加少量料酒、生抽抓匀腌制。",
            "皮蛋切小丁，生姜切细丝。",
            "锅中烧水，水开下大米，大火煮 10 分钟后转小火熬 25 分钟。",
            "粥底绵稠后加入姜丝和瘦肉丝，搅散煮 3 分钟至肉变色。",
            "加入皮蛋碎，搅匀再煮 2 分钟。加盐和白胡椒粉调味出锅。",
        ],
        "nutrition_per_serving": {"calories": 350, "protein_g": 18.0, "fat_g": 12.0, "carbs_g": 42.0},
        "serving_size": "1大碗（约400g）",
        "tags": ["high_protein", "comfort_food"],
        "suitable_goal": "all",
    },
    {
        "name": "番茄鸡蛋面",
        "category": "chinese",
        "meal_type": "breakfast",
        "cooking_method": "boil",
        "prep_time_min": 5,
        "cook_time_min": 15,
        "difficulty": "easy",
        "ingredients": [
            {"name": "面条", "amount_g": 150},
            {"name": "番茄", "amount_g": 150},
            {"name": "鸡蛋", "amount_g": 100},
            {"name": "葱", "amount_g": 5},
            {"name": "水", "amount_g": 500},
        ],
        "steps": [
            "番茄顶端划十字，开水烫 1 分钟去皮，切小块。",
            "鸡蛋打散，加少许盐搅匀。",
            "热锅少油，蛋液下锅炒散凝固后盛出。",
            "锅中再加少许油，番茄块下锅炒至出汁软烂。",
            "加 500ml 水烧开，下面条煮至断生。",
            "放入炒好的鸡蛋，加盐和少许生抽调味，撒葱花出锅。",
        ],
        "nutrition_per_serving": {"calories": 430, "protein_g": 18.0, "fat_g": 12.0, "carbs_g": 58.0},
        "serving_size": "1大碗（约500g）",
        "tags": ["quick", "comfort_food"],
        "suitable_goal": "all",
    },
    {
        "name": "葱油拌面",
        "category": "chinese",
        "meal_type": "breakfast",
        "cooking_method": "boil",
        "prep_time_min": 5,
        "cook_time_min": 15,
        "difficulty": "easy",
        "ingredients": [
            {"name": "面条", "amount_g": 150},
            {"name": "葱", "amount_g": 40},
            {"name": "生抽", "amount_g": 15},
            {"name": "花生油", "amount_g": 20},
        ],
        "steps": [
            "小葱洗净切寸段，葱白和葱叶分开。",
            "锅中倒油，冷油下葱白段，小火慢炸至微黄。",
            "加入葱叶段继续炸至焦黄色，关火滤出葱油。",
            "炸好的葱段挑出，加生抽和老抽拌匀成葱油酱汁。",
            "面条下开水煮熟捞出沥干，趁热拌入葱油酱汁。",
            "拌匀后装盘，撒上炸葱段即可。",
        ],
        "nutrition_per_serving": {"calories": 480, "protein_g": 11.0, "fat_g": 20.0, "carbs_g": 60.0},
        "serving_size": "1盘（约250g）",
        "tags": ["quick", "comfort_food"],
        "suitable_goal": "maintain",
    },
    {
        "name": "水煮鸡蛋配紫薯",
        "category": "chinese",
        "meal_type": "breakfast",
        "cooking_method": "boil",
        "prep_time_min": 2,
        "cook_time_min": 20,
        "difficulty": "easy",
        "ingredients": [
            {"name": "鸡蛋", "amount_g": 150},
            {"name": "紫薯", "amount_g": 200},
            {"name": "水", "amount_g": 1000},
        ],
        "steps": [
            "鸡蛋冷水下锅，水沸后计时煮 8 分钟（溏心）或 10 分钟（全熟）。",
            "紫薯洗净，不去皮，放入蒸锅或水中煮 15-20 分钟至筷子可轻松穿透。",
            "鸡蛋捞出过冷水，剥壳对半切开。",
            "紫薯去皮切块，与鸡蛋一同摆盘。可撒少许黑胡椒调味。",
        ],
        "nutrition_per_serving": {"calories": 330, "protein_g": 20.0, "fat_g": 13.0, "carbs_g": 30.0},
        "serving_size": "1份",
        "tags": ["high_protein", "low_fat", "meal_prep"],
        "suitable_goal": "build_muscle",
    },
    {
        "name": "蒸蛋羹",
        "category": "chinese",
        "meal_type": "breakfast",
        "cooking_method": "steam",
        "prep_time_min": 5,
        "cook_time_min": 12,
        "difficulty": "easy",
        "ingredients": [
            {"name": "鸡蛋", "amount_g": 150},
            {"name": "温水", "amount_g": 200},
            {"name": "生抽", "amount_g": 5},
            {"name": "芝麻油", "amount_g": 3},
        ],
        "steps": [
            "鸡蛋打散，加 1.5 倍温水（约 40℃），加少许盐搅匀。",
            "用细筛过滤蛋液 2 次，去除蛋筋和气泡。",
            "蛋液倒入深碗，盖上保鲜膜，用牙签扎几个小孔。",
            "蒸锅中水烧开，放入蛋液碗，中火蒸 10-12 分钟。",
            "取出后淋少许生抽和几滴芝麻油，撒葱花即可。",
        ],
        "nutrition_per_serving": {"calories": 230, "protein_g": 20.0, "fat_g": 13.0, "carbs_g": 5.0},
        "serving_size": "1碗（约250g）",
        "tags": ["high_protein", "low_carb", "easy_digest"],
        "suitable_goal": "build_muscle",
    },
    {
        "name": "鸡蛋灌饼",
        "category": "chinese",
        "meal_type": "breakfast",
        "cooking_method": "stir_fry",
        "prep_time_min": 10,
        "cook_time_min": 10,
        "difficulty": "medium",
        "ingredients": [
            {"name": "面粉", "amount_g": 100},
            {"name": "鸡蛋", "amount_g": 100},
            {"name": "生菜", "amount_g": 30},
            {"name": "花生油", "amount_g": 8},
        ],
        "steps": [
            "面粉加温水揉成光滑面团，醒面 20 分钟。",
            "面团擀成薄饼皮。热锅刷薄油，中火放入饼皮。",
            "饼皮鼓起大泡时，用筷子戳开小口，倒入打散的蛋液。",
            "翻面再烙 1 分钟至两面金黄。",
            "取出后刷一层甜面酱或辣酱，铺上生菜叶，卷起即可。",
        ],
        "nutrition_per_serving": {"calories": 420, "protein_g": 18.0, "fat_g": 16.0, "carbs_g": 50.0},
        "serving_size": "1个（约200g）",
        "tags": ["street_food", "quick"],
        "suitable_goal": "all",
    },
    {
        "name": "紫薯燕麦粥",
        "category": "chinese",
        "meal_type": "breakfast",
        "cooking_method": "boil",
        "prep_time_min": 5,
        "cook_time_min": 20,
        "difficulty": "easy",
        "ingredients": [
            {"name": "燕麦片", "amount_g": 50},
            {"name": "紫薯", "amount_g": 150},
            {"name": "牛奶", "amount_g": 100},
            {"name": "水", "amount_g": 400},
        ],
        "steps": [
            "紫薯去皮切小丁。",
            "锅中加 400ml 水，放入紫薯丁，大火煮开转中小火煮 10 分钟。",
            "加入燕麦片，继续煮 5 分钟，期间搅拌防止粘底。",
            "粥变得浓稠时倒入牛奶，搅匀加热 1 分钟后关火。",
            "盛入碗中，可撒少许枸杞点缀。",
        ],
        "nutrition_per_serving": {"calories": 320, "protein_g": 11.0, "fat_g": 5.5, "carbs_g": 56.0},
        "serving_size": "1大碗（约350g）",
        "tags": ["high_fiber", "low_fat", "vegetarian"],
        "suitable_goal": "lose_fat",
    },
    {
        "name": "五谷豆浆配花卷",
        "category": "chinese",
        "meal_type": "breakfast",
        "cooking_method": "steam",
        "prep_time_min": 10,
        "cook_time_min": 25,
        "difficulty": "easy",
        "ingredients": [
            {"name": "黄豆", "amount_g": 50},
            {"name": "小米", "amount_g": 15},
            {"name": "花生", "amount_g": 10},
            {"name": "红枣", "amount_g": 10},
            {"name": "花卷", "amount_g": 100},
            {"name": "水", "amount_g": 800},
        ],
        "steps": [
            "黄豆、花生提前浸泡 4 小时以上（或隔夜）。",
            "小米和去核红枣洗净。所有食材放入豆浆机。",
            "加水至水位线，启动「五谷豆浆」模式。",
            "花卷放入蒸锅，上汽后蒸 8 分钟。",
            "豆浆打完后过滤（可选），与蒸好的花卷一起上桌。",
        ],
        "nutrition_per_serving": {"calories": 380, "protein_g": 16.0, "fat_g": 8.0, "carbs_g": 60.0},
        "serving_size": "1份",
        "tags": ["high_fiber", "vegetarian"],
        "suitable_goal": "all",
    },
    {
        "name": "全麦鸡蛋三明治",
        "category": "western",
        "meal_type": "breakfast",
        "cooking_method": "raw",
        "prep_time_min": 10,
        "cook_time_min": 8,
        "difficulty": "easy",
        "ingredients": [
            {"name": "全麦面包", "amount_g": 80},
            {"name": "鸡蛋", "amount_g": 100},
            {"name": "生菜", "amount_g": 20},
            {"name": "番茄", "amount_g": 50},
            {"name": "黄瓜", "amount_g": 30},
        ],
        "steps": [
            "鸡蛋冷水下锅，水沸后煮 8 分钟，过凉水剥壳切片。",
            "番茄和黄瓜洗净切薄片，生菜叶洗净沥干。",
            "全麦面包放入烤面包机烤至微脆（或不烤直接使用）。",
            "在面包上依次铺生菜、番茄片、黄瓜片、鸡蛋片。",
            "盖上另一片面包，对角切开即可。可搭配少许低脂沙拉酱。",
        ],
        "nutrition_per_serving": {"calories": 340, "protein_g": 20.0, "fat_g": 12.0, "carbs_g": 38.0},
        "serving_size": "1份",
        "tags": ["high_protein", "high_fiber", "meal_prep"],
        "suitable_goal": "build_muscle",
    },

    # ── 午餐 (15) ──────────────────────────────────────────────
    {
        "name": "宫保鸡丁",
        "category": "chinese",
        "meal_type": "lunch",
        "cooking_method": "stir_fry",
        "prep_time_min": 15,
        "cook_time_min": 10,
        "difficulty": "medium",
        "ingredients": [
            {"name": "鸡胸肉", "amount_g": 200},
            {"name": "花生", "amount_g": 30},
            {"name": "黄瓜", "amount_g": 50},
            {"name": "胡萝卜", "amount_g": 50},
            {"name": "干辣椒", "amount_g": 5},
            {"name": "大蒜", "amount_g": 5},
            {"name": "花生油", "amount_g": 15},
        ],
        "steps": [
            "鸡胸肉切 1.5cm 丁，加料酒、生抽、淀粉抓匀腌制 15 分钟。",
            "黄瓜和胡萝卜切丁，蒜切末，干辣椒剪段去籽。",
            "调碗汁：生抽、醋、糖、淀粉、水拌匀备用。",
            "热锅凉油，小火将花生米炸至微黄酥脆，捞出。",
            "锅中留底油，爆香干辣椒段和蒜末。",
            "下鸡丁大火翻炒至变色，加入胡萝卜丁翻炒 1 分钟。",
            "倒入碗汁，快速翻炒均匀收汁。关火前加入黄瓜丁和花生米翻匀出锅。",
        ],
        "nutrition_per_serving": {"calories": 450, "protein_g": 38.0, "fat_g": 22.0, "carbs_g": 18.0},
        "serving_size": "1盘（约300g）",
        "tags": ["high_protein", "classic"],
        "suitable_goal": "build_muscle",
    },
    {
        "name": "鱼香肉丝",
        "category": "chinese",
        "meal_type": "lunch",
        "cooking_method": "stir_fry",
        "prep_time_min": 20,
        "cook_time_min": 8,
        "difficulty": "medium",
        "ingredients": [
            {"name": "猪瘦肉", "amount_g": 150},
            {"name": "木耳", "amount_g": 50},
            {"name": "胡萝卜", "amount_g": 50},
            {"name": "青椒", "amount_g": 40},
            {"name": "大蒜", "amount_g": 5},
            {"name": "生姜", "amount_g": 5},
            {"name": "花生油", "amount_g": 15},
        ],
        "steps": [
            "猪瘦肉切丝，加料酒、生抽、淀粉抓匀腌制 15 分钟。",
            "木耳提前泡发焯水后切丝，胡萝卜、青椒切丝。",
            "调鱼香汁：生抽、醋、糖、淀粉、清水拌匀。",
            "热锅凉油，下肉丝滑炒至变色盛出。",
            "锅中底油爆香蒜末姜末，加入豆瓣酱炒出红油。",
            "下胡萝卜丝、木耳丝、青椒丝大火翻炒 1 分钟。",
            "倒回肉丝，淋入鱼香汁，大火快速翻炒收汁出锅。",
        ],
        "nutrition_per_serving": {"calories": 380, "protein_g": 28.0, "fat_g": 20.0, "carbs_g": 18.0},
        "serving_size": "1盘（约280g）",
        "tags": ["classic", "high_protein"],
        "suitable_goal": "all",
    },
    {
        "name": "番茄牛腩",
        "category": "chinese",
        "meal_type": "lunch",
        "cooking_method": "boil",
        "prep_time_min": 20,
        "cook_time_min": 90,
        "difficulty": "medium",
        "ingredients": [
            {"name": "牛肉", "amount_g": 250},
            {"name": "番茄", "amount_g": 200},
            {"name": "土豆", "amount_g": 100},
            {"name": "洋葱", "amount_g": 80},
            {"name": "生姜", "amount_g": 10},
            {"name": "番茄酱", "amount_g": 30},
        ],
        "steps": [
            "牛腩切 3cm 块，冷水下锅焯水去血沫，捞出洗净。",
            "番茄顶端划十字开水烫后去皮切块，土豆和洋葱切块。",
            "热锅少许油，下姜片和洋葱炒香。",
            "加入牛腩块翻炒至表面微黄，倒入番茄块炒出汁。",
            "加番茄酱、生抽和没过食材的热水，大火烧开转小火炖 70 分钟。",
            "加入土豆块继续炖 15 分钟至软烂。加盐调味即可。",
        ],
        "nutrition_per_serving": {"calories": 520, "protein_g": 42.0, "fat_g": 15.0, "carbs_g": 48.0},
        "serving_size": "1份（约350g）",
        "tags": ["high_protein", "comfort_food"],
        "suitable_goal": "build_muscle",
    },
    {
        "name": "回锅肉",
        "category": "chinese",
        "meal_type": "lunch",
        "cooking_method": "stir_fry",
        "prep_time_min": 10,
        "cook_time_min": 10,
        "difficulty": "medium",
        "ingredients": [
            {"name": "猪瘦肉", "amount_g": 200},
            {"name": "青椒", "amount_g": 80},
            {"name": "蒜苗", "amount_g": 50},
            {"name": "生姜", "amount_g": 5},
            {"name": "大蒜", "amount_g": 5},
            {"name": "花生油", "amount_g": 12},
        ],
        "steps": [
            "猪肉整块冷水下锅，加姜片、料酒煮至筷子可扎透（约 20 分钟）。",
            "捞出放凉后切薄片（约 3mm 厚），青椒切块，蒜苗斜切段。",
            "热锅少油，下肉片中火煸炒至边缘微卷出油。",
            "将肉推至锅边，下豆瓣酱炒出红油。",
            "加入蒜末和姜片炒香，放入青椒块大火翻炒至断生。",
            "最后加入蒜苗段、少许生抽和糖，快速翻炒均匀出锅。",
        ],
        "nutrition_per_serving": {"calories": 420, "protein_g": 32.0, "fat_g": 25.0, "carbs_g": 10.0},
        "serving_size": "1盘（约280g）",
        "tags": ["classic", "high_protein"],
        "suitable_goal": "all",
    },
    {
        "name": "蒜蓉西兰花炒虾仁",
        "category": "chinese",
        "meal_type": "lunch",
        "cooking_method": "stir_fry",
        "prep_time_min": 10,
        "cook_time_min": 8,
        "difficulty": "easy",
        "ingredients": [
            {"name": "虾仁", "amount_g": 150},
            {"name": "西兰花", "amount_g": 200},
            {"name": "大蒜", "amount_g": 10},
            {"name": "花生油", "amount_g": 10},
        ],
        "steps": [
            "虾仁开背去虾线，加料酒、盐、淀粉抓匀腌制 10 分钟。",
            "西兰花掰成小朵，沸水加盐焯烫 1 分钟捞出沥干。",
            "大蒜剁成蒜蓉。热锅凉油，小火将一半蒜蓉煸至金黄。",
            "转大火，下虾仁快速滑炒至变色。",
            "加入西兰花和剩余生蒜蓉，快速翻炒 1 分钟。",
            "加盐和少许蚝油调味，炒匀出锅。",
        ],
        "nutrition_per_serving": {"calories": 280, "protein_g": 32.0, "fat_g": 10.0, "carbs_g": 12.0},
        "serving_size": "1盘（约300g）",
        "tags": ["high_protein", "low_fat", "low_carb", "quick"],
        "suitable_goal": "lose_fat",
    },
    {
        "name": "麻婆豆腐",
        "category": "chinese",
        "meal_type": "lunch",
        "cooking_method": "stir_fry",
        "prep_time_min": 10,
        "cook_time_min": 10,
        "difficulty": "medium",
        "ingredients": [
            {"name": "豆腐", "amount_g": 300},
            {"name": "猪肉末", "amount_g": 50},
            {"name": "大蒜", "amount_g": 5},
            {"name": "生姜", "amount_g": 5},
            {"name": "花椒粉", "amount_g": 2},
            {"name": "花生油", "amount_g": 10},
        ],
        "steps": [
            "嫩豆腐切 2cm 方块，沸水加盐焯 2 分钟捞出沥干。",
            "热锅凉油，下猪肉末煸炒至酥香吐油。",
            "加入豆瓣酱炒出红油，再加蒜末姜末炒香。",
            "加适量清水或高汤（约 150ml），烧开后放入豆腐块。",
            "中火煮 3-5 分钟让豆腐入味，轻轻推动防止粘锅。",
            "分两次淋入水淀粉勾芡，汤汁浓稠后撒花椒粉和葱花出锅。",
        ],
        "nutrition_per_serving": {"calories": 330, "protein_g": 24.0, "fat_g": 18.0, "carbs_g": 12.0},
        "serving_size": "1盘（约300g）",
        "tags": ["classic", "high_protein"],
        "suitable_goal": "all",
    },
    {
        "name": "青椒肉丝",
        "category": "chinese",
        "meal_type": "lunch",
        "cooking_method": "stir_fry",
        "prep_time_min": 10,
        "cook_time_min": 6,
        "difficulty": "easy",
        "ingredients": [
            {"name": "猪瘦肉", "amount_g": 150},
            {"name": "青椒", "amount_g": 150},
            {"name": "生姜", "amount_g": 5},
            {"name": "花生油", "amount_g": 12},
        ],
        "steps": [
            "猪瘦肉切丝，加料酒、生抽、淀粉抓匀腌制 10 分钟。",
            "青椒去籽切丝，生姜切细丝。",
            "热锅凉油，下姜丝爆香。",
            "下肉丝大火快速滑炒至变色盛出。",
            "锅中余油下青椒丝大火翻炒至断生。",
            "倒回肉丝，加盐和少许生抽快速翻炒均匀出锅。",
        ],
        "nutrition_per_serving": {"calories": 310, "protein_g": 26.0, "fat_g": 16.0, "carbs_g": 8.0},
        "serving_size": "1盘（约260g）",
        "tags": ["quick", "high_protein", "classic"],
        "suitable_goal": "all",
    },
    {
        "name": "红烧鲫鱼",
        "category": "chinese",
        "meal_type": "lunch",
        "cooking_method": "stir_fry",
        "prep_time_min": 15,
        "cook_time_min": 20,
        "difficulty": "medium",
        "ingredients": [
            {"name": "鲫鱼", "amount_g": 400},
            {"name": "生姜", "amount_g": 10},
            {"name": "大蒜", "amount_g": 10},
            {"name": "葱", "amount_g": 15},
            {"name": "花生油", "amount_g": 20},
        ],
        "steps": [
            "鲫鱼去鳞去腮去内脏清洗干净，鱼身两面各划三刀。",
            "用厨房纸吸干鱼身水分，两面拍薄薄一层面粉。",
            "热锅倒油，油热后下姜片，放入鱼中小火煎至两面金黄（每面约 3 分钟）。",
            "加入蒜瓣、葱段，淋入料酒、生抽、老抽。",
            "加开水没过鱼身一半，加少许糖和醋提鲜。",
            "大火烧开转中火烧 10 分钟，期间将汤汁不断浇在鱼身上使其入味。",
            "最后大火收汁，汤汁浓稠后撒葱花出锅。",
        ],
        "nutrition_per_serving": {"calories": 380, "protein_g": 35.0, "fat_g": 18.0, "carbs_g": 6.0},
        "serving_size": "1条（约350g）",
        "tags": ["high_protein", "classic"],
        "suitable_goal": "all",
    },
    {
        "name": "孜然牛肉",
        "category": "chinese",
        "meal_type": "lunch",
        "cooking_method": "stir_fry",
        "prep_time_min": 15,
        "cook_time_min": 8,
        "difficulty": "medium",
        "ingredients": [
            {"name": "牛腱子", "amount_g": 200},
            {"name": "洋葱", "amount_g": 80},
            {"name": "青椒", "amount_g": 50},
            {"name": "孜然粉", "amount_g": 3},
            {"name": "辣椒面", "amount_g": 2},
            {"name": "花生油", "amount_g": 12},
        ],
        "steps": [
            "牛肉逆纹切薄片，加料酒、生抽、淀粉、少许小苏打抓匀腌制 20 分钟。",
            "洋葱和青椒切丝。热锅凉油，大火将牛肉滑炒至变色盛出。",
            "锅中底油炒香洋葱丝至半透明。",
            "倒回牛肉，加孜然粉、辣椒面、盐快速翻炒均匀。",
            "最后加入青椒丝翻炒 30 秒出锅，撒上白芝麻点缀。",
        ],
        "nutrition_per_serving": {"calories": 360, "protein_g": 38.0, "fat_g": 16.0, "carbs_g": 10.0},
        "serving_size": "1盘（约260g）",
        "tags": ["high_protein", "low_carb"],
        "suitable_goal": "build_muscle",
    },
    {
        "name": "蒜蓉粉丝蒸娃娃菜",
        "category": "chinese",
        "meal_type": "lunch",
        "cooking_method": "steam",
        "prep_time_min": 10,
        "cook_time_min": 10,
        "difficulty": "easy",
        "ingredients": [
            {"name": "娃娃菜", "amount_g": 200},
            {"name": "粉条", "amount_g": 40},
            {"name": "大蒜", "amount_g": 15},
            {"name": "生抽", "amount_g": 10},
            {"name": "花生油", "amount_g": 8},
        ],
        "steps": [
            "粉丝温水泡软剪短，娃娃菜对半切开。",
            "大蒜剁成蒜蓉，一半下油锅小火炸至金黄成金银蒜。",
            "盘中铺粉丝，摆上娃娃菜。",
            "将生熟蒜蓉混合，加生抽、蚝油拌匀，均匀铺在娃娃菜上。",
            "上蒸锅大火蒸 8-10 分钟。",
            "出锅后淋少许热油激发香气即可。",
        ],
        "nutrition_per_serving": {"calories": 180, "protein_g": 4.0, "fat_g": 8.0, "carbs_g": 22.0},
        "serving_size": "1盘（约250g）",
        "tags": ["vegetarian", "low_calorie", "quick"],
        "suitable_goal": "lose_fat",
    },
    {
        "name": "酸辣土豆丝",
        "category": "chinese",
        "meal_type": "lunch",
        "cooking_method": "stir_fry",
        "prep_time_min": 10,
        "cook_time_min": 5,
        "difficulty": "easy",
        "ingredients": [
            {"name": "土豆", "amount_g": 250},
            {"name": "干辣椒", "amount_g": 5},
            {"name": "花椒", "amount_g": 1},
            {"name": "醋", "amount_g": 15},
            {"name": "花生油", "amount_g": 10},
        ],
        "steps": [
            "土豆去皮切细丝，放清水中浸泡去除淀粉，换水 2-3 次至水清澈。",
            "捞出沥干水分。干辣椒剪段去籽。",
            "热锅凉油，小火炸香花椒后捞出弃用。",
            "下干辣椒段爆香，转大火下土豆丝快速翻炒。",
            "炒至土豆丝变透明（约 2 分钟），沿锅边淋入醋。",
            "加盐翻炒均匀，出锅前可再加少许醋增香。",
        ],
        "nutrition_per_serving": {"calories": 210, "protein_g": 4.0, "fat_g": 10.0, "carbs_g": 26.0},
        "serving_size": "1盘（约250g）",
        "tags": ["vegetarian", "quick", "classic"],
        "suitable_goal": "lose_fat",
    },
    {
        "name": "香菇滑鸡",
        "category": "chinese",
        "meal_type": "lunch",
        "cooking_method": "steam",
        "prep_time_min": 15,
        "cook_time_min": 18,
        "difficulty": "easy",
        "ingredients": [
            {"name": "鸡腿肉", "amount_g": 250},
            {"name": "香菇", "amount_g": 80},
            {"name": "生姜", "amount_g": 8},
            {"name": "葱", "amount_g": 10},
        ],
        "steps": [
            "干香菇提前泡发切块，新鲜香菇洗净去蒂切块。",
            "鸡腿肉去骨切块，加姜丝、料酒、生抽、淀粉、少许糖抓匀腌制 20 分钟。",
            "将腌好的鸡块与香菇混合，淋少许芝麻油拌匀。",
            "放入深盘中铺平，不要叠放。",
            "蒸锅水开后将盘子放入，大火蒸 15-18 分钟。",
            "出锅后撒葱花，淋少许热油即可。",
        ],
        "nutrition_per_serving": {"calories": 350, "protein_g": 35.0, "fat_g": 18.0, "carbs_g": 8.0},
        "serving_size": "1盘（约280g）",
        "tags": ["high_protein", "low_carb", "meal_prep"],
        "suitable_goal": "build_muscle",
    },
    {
        "name": "地三鲜",
        "category": "chinese",
        "meal_type": "lunch",
        "cooking_method": "stir_fry",
        "prep_time_min": 15,
        "cook_time_min": 12,
        "difficulty": "medium",
        "ingredients": [
            {"name": "土豆", "amount_g": 150},
            {"name": "茄子", "amount_g": 150},
            {"name": "青椒", "amount_g": 100},
            {"name": "大蒜", "amount_g": 8},
            {"name": "花生油", "amount_g": 25},
        ],
        "steps": [
            "土豆去皮切片，茄子切滚刀块，青椒掰小块。",
            "茄子块撒盐腌 10 分钟挤去水分，拍薄薄一层淀粉。",
            "锅中多倒油，分别将土豆片和茄子块煎至金黄捞出。",
            "锅中留底油，爆香蒜末，下青椒翻炒至断生。",
            "倒回土豆片和茄子块，淋入生抽、少许糖和水。",
            "大火翻炒收汁，加盐调味，出锅前勾薄芡。",
        ],
        "nutrition_per_serving": {"calories": 360, "protein_g": 6.0, "fat_g": 25.0, "carbs_g": 30.0},
        "serving_size": "1盘（约350g）",
        "tags": ["vegetarian", "classic"],
        "suitable_goal": "all",
    },
    {
        "name": "糖醋里脊",
        "category": "chinese",
        "meal_type": "lunch",
        "cooking_method": "stir_fry",
        "prep_time_min": 20,
        "cook_time_min": 10,
        "difficulty": "medium",
        "ingredients": [
            {"name": "猪瘦肉", "amount_g": 200},
            {"name": "鸡蛋", "amount_g": 50},
            {"name": "面粉", "amount_g": 30},
            {"name": "番茄酱", "amount_g": 30},
            {"name": "醋", "amount_g": 10},
            {"name": "花生油", "amount_g": 25},
        ],
        "steps": [
            "猪瘦肉切条，加料酒、盐腌制 10 分钟。",
            "调制糖醋汁：番茄酱、醋、糖、水拌匀。",
            "面糊用面粉、鸡蛋、少许水调成可挂筷的稠度。",
            "肉条裹面糊，油温 170℃ 下锅炸至金黄捞出。",
            "待油温升至 180℃ 再次复炸 30 秒使其更酥脆。",
            "锅中留少许底油，倒入糖醋汁小火熬至冒泡浓稠。",
            "放入炸好的肉条快速翻匀，撒白芝麻出锅。",
        ],
        "nutrition_per_serving": {"calories": 520, "protein_g": 32.0, "fat_g": 28.0, "carbs_g": 30.0},
        "serving_size": "1盘（约250g）",
        "tags": ["classic", "comfort_food"],
        "suitable_goal": "build_muscle",
    },
    {
        "name": "蚝油生菜",
        "category": "chinese",
        "meal_type": "lunch",
        "cooking_method": "stir_fry",
        "prep_time_min": 5,
        "cook_time_min": 3,
        "difficulty": "easy",
        "ingredients": [
            {"name": "生菜", "amount_g": 300},
            {"name": "大蒜", "amount_g": 10},
            {"name": "蚝油", "amount_g": 15},
            {"name": "花生油", "amount_g": 8},
        ],
        "steps": [
            "生菜逐叶洗净沥干。大蒜剁成蒜蓉。",
            "调碗汁：蚝油、生抽、少许糖和清水搅匀。",
            "锅中烧水，加少许油和盐，水开后生菜下锅烫 20 秒捞出入盘。",
            "另起锅少油，小火将蒜蓉煸至微黄。",
            "倒入碗汁烧开，略微收浓。",
            "将蚝油蒜蓉汁浇在生菜上即可。",
        ],
        "nutrition_per_serving": {"calories": 90, "protein_g": 3.0, "fat_g": 6.0, "carbs_g": 8.0},
        "serving_size": "1盘（约200g）",
        "tags": ["vegetarian", "low_calorie", "quick"],
        "suitable_goal": "lose_fat",
    },

    # ── 晚餐 (15) ──────────────────────────────────────────────
    {
        "name": "清蒸鲈鱼",
        "category": "chinese",
        "meal_type": "dinner",
        "cooking_method": "steam",
        "prep_time_min": 15,
        "cook_time_min": 10,
        "difficulty": "medium",
        "ingredients": [
            {"name": "鲈鱼", "amount_g": 400},
            {"name": "生姜", "amount_g": 15},
            {"name": "葱", "amount_g": 20},
            {"name": "生抽", "amount_g": 15},
        ],
        "steps": [
            "鲈鱼去鳞去腮去内脏，清洗干净后在鱼身两面各划三刀。",
            "盘中铺姜片和葱段垫底，放上鱼。鱼身和鱼腹也塞入姜片和葱段。",
            "蒸锅水开后放入鱼盘，大火蒸 8-10 分钟（视鱼大小而定）。",
            "蒸好后倒掉盘中腥水，拣去葱姜。",
            "鱼身放上新切的葱丝和姜丝。",
            "淋上蒸鱼豉油，另起锅将油烧至冒烟，浇在葱姜丝上激香即可。",
        ],
        "nutrition_per_serving": {"calories": 260, "protein_g": 36.0, "fat_g": 10.0, "carbs_g": 2.0},
        "serving_size": "1条（约350g）",
        "tags": ["high_protein", "low_fat", "low_carb"],
        "suitable_goal": "lose_fat",
    },
    {
        "name": "西兰花炒鸡胸",
        "category": "chinese",
        "meal_type": "dinner",
        "cooking_method": "stir_fry",
        "prep_time_min": 10,
        "cook_time_min": 8,
        "difficulty": "easy",
        "ingredients": [
            {"name": "鸡胸肉", "amount_g": 200},
            {"name": "西兰花", "amount_g": 200},
            {"name": "大蒜", "amount_g": 5},
            {"name": "花生油", "amount_g": 8},
        ],
        "steps": [
            "鸡胸肉切薄片，加料酒、生抽、淀粉抓匀腌制 15 分钟。",
            "西兰花掰成小朵，沸水加盐焯 1 分钟捞出。",
            "热锅少油，大蒜切片爆香。",
            "下鸡胸肉片大火滑炒至变色。",
            "加入西兰花快速翻炒 1 分钟，加盐和少许蚝油调味出锅。",
        ],
        "nutrition_per_serving": {"calories": 290, "protein_g": 38.0, "fat_g": 9.0, "carbs_g": 10.0},
        "serving_size": "1盘（约320g）",
        "tags": ["high_protein", "low_fat", "low_carb", "quick", "meal_prep"],
        "suitable_goal": "lose_fat",
    },
    {
        "name": "番茄菌菇汤",
        "category": "soup",
        "meal_type": "dinner",
        "cooking_method": "boil",
        "prep_time_min": 10,
        "cook_time_min": 15,
        "difficulty": "easy",
        "ingredients": [
            {"name": "番茄", "amount_g": 150},
            {"name": "蘑菇", "amount_g": 100},
            {"name": "豆腐", "amount_g": 150},
            {"name": "鸡蛋", "amount_g": 50},
            {"name": "水", "amount_g": 500},
        ],
        "steps": [
            "番茄去皮切块，蘑菇切片，豆腐切小块。",
            "热锅少油，番茄块下锅炒至出汁软烂。",
            "加 500ml 水烧开，放入蘑菇片煮 3 分钟。",
            "加入豆腐块，中火继续煮 5 分钟。",
            "鸡蛋打散，沿锅边缓缓淋入成蛋花。",
            "加盐、白胡椒粉调味，撒葱花出锅。",
        ],
        "nutrition_per_serving": {"calories": 200, "protein_g": 18.0, "fat_g": 8.0, "carbs_g": 15.0},
        "serving_size": "1大碗（约400g）",
        "tags": ["low_fat", "high_protein", "easy_digest"],
        "suitable_goal": "lose_fat",
    },
    {
        "name": "凉拌黄瓜",
        "category": "chinese",
        "meal_type": "dinner",
        "cooking_method": "raw",
        "prep_time_min": 10,
        "cook_time_min": 0,
        "difficulty": "easy",
        "ingredients": [
            {"name": "黄瓜", "amount_g": 250},
            {"name": "大蒜", "amount_g": 8},
            {"name": "醋", "amount_g": 10},
            {"name": "生抽", "amount_g": 8},
            {"name": "芝麻油", "amount_g": 3},
        ],
        "steps": [
            "黄瓜洗净，用刀背拍裂后切段。",
            "大蒜剁成蒜蓉，干辣椒剪段（可选）。",
            "调凉拌汁：蒜蓉、生抽、醋、少许糖和盐、芝麻油搅匀。",
            "将凉拌汁浇在黄瓜上拌匀。",
            "静置 5 分钟入味后装盘即可。",
        ],
        "nutrition_per_serving": {"calories": 70, "protein_g": 2.0, "fat_g": 3.0, "carbs_g": 8.0},
        "serving_size": "1盘（约200g）",
        "tags": ["low_calorie", "vegetarian", "quick", "low_carb"],
        "suitable_goal": "lose_fat",
    },
    {
        "name": "虾仁豆腐煲",
        "category": "chinese",
        "meal_type": "dinner",
        "cooking_method": "boil",
        "prep_time_min": 15,
        "cook_time_min": 15,
        "difficulty": "easy",
        "ingredients": [
            {"name": "虾仁", "amount_g": 120},
            {"name": "豆腐", "amount_g": 250},
            {"name": "白菜", "amount_g": 100},
            {"name": "生姜", "amount_g": 5},
            {"name": "花生油", "amount_g": 6},
        ],
        "steps": [
            "虾仁开背去虾线，加料酒、盐腌 10 分钟。",
            "豆腐切块，白菜洗净撕小片。",
            "砂锅（或汤锅）底刷薄油，铺上姜丝和葱段。",
            "依次放入白菜、豆腐块、虾仁。",
            "加高汤或清水至食材三分之二高度，大火烧开。",
            "转中小火煲 10 分钟，加盐和白胡椒调味即可。",
        ],
        "nutrition_per_serving": {"calories": 250, "protein_g": 28.0, "fat_g": 8.0, "carbs_g": 12.0},
        "serving_size": "1煲（约350g）",
        "tags": ["high_protein", "low_fat", "easy_digest"],
        "suitable_goal": "lose_fat",
    },
    {
        "name": "清炒菠菜",
        "category": "chinese",
        "meal_type": "dinner",
        "cooking_method": "stir_fry",
        "prep_time_min": 5,
        "cook_time_min": 3,
        "difficulty": "easy",
        "ingredients": [
            {"name": "菠菜", "amount_g": 300},
            {"name": "大蒜", "amount_g": 8},
            {"name": "花生油", "amount_g": 8},
        ],
        "steps": [
            "菠菜去根洗净，大蒜切片。",
            "锅中烧水，水开后菠菜下锅焯水 30 秒去除草酸，捞出沥干。",
            "热锅凉油，蒜片爆香。",
            "下菠菜大火快速翻炒 1 分钟。",
            "加盐调味即可出锅。",
        ],
        "nutrition_per_serving": {"calories": 95, "protein_g": 5.0, "fat_g": 7.0, "carbs_g": 6.0},
        "serving_size": "1盘（约180g）",
        "tags": ["low_calorie", "vegetarian", "quick", "low_carb"],
        "suitable_goal": "lose_fat",
    },
    {
        "name": "冬瓜排骨汤",
        "category": "soup",
        "meal_type": "dinner",
        "cooking_method": "boil",
        "prep_time_min": 15,
        "cook_time_min": 60,
        "difficulty": "easy",
        "ingredients": [
            {"name": "猪排骨", "amount_g": 200},
            {"name": "冬瓜", "amount_g": 250},
            {"name": "生姜", "amount_g": 10},
            {"name": "水", "amount_g": 1000},
        ],
        "steps": [
            "排骨冷水下锅焯水，煮沸后撇去浮沫，捞出洗净。",
            "冬瓜去皮去瓤切大块（约 4cm）。",
            "将排骨、姜片放入汤锅，加足量水大火烧开。",
            "转小火炖 40 分钟至排骨软烂。",
            "加入冬瓜块继续炖 10-15 分钟至冬瓜半透明。",
            "加盐调味，撒葱花即可。",
        ],
        "nutrition_per_serving": {"calories": 320, "protein_g": 22.0, "fat_g": 18.0, "carbs_g": 14.0},
        "serving_size": "1大碗（约450g）",
        "tags": ["comfort_food", "easy_digest"],
        "suitable_goal": "maintain",
    },
    {
        "name": "蒜蓉秋葵",
        "category": "chinese",
        "meal_type": "dinner",
        "cooking_method": "boil",
        "prep_time_min": 5,
        "cook_time_min": 5,
        "difficulty": "easy",
        "ingredients": [
            {"name": "秋葵", "amount_g": 200},
            {"name": "大蒜", "amount_g": 10},
            {"name": "生抽", "amount_g": 10},
            {"name": "花生油", "amount_g": 5},
        ],
        "steps": [
            "秋葵洗净不要去蒂（防止粘液流失）。",
            "锅中烧水，水开后加少许盐和油，放入秋葵焯 2 分钟。",
            "捞出过凉开水，沥干后切去蒂部，对半切开摆盘。",
            "大蒜剁成蒜蓉，热锅少油小火煸至微黄。",
            "加入生抽和少许水烧开，浇在秋葵上即可。",
        ],
        "nutrition_per_serving": {"calories": 90, "protein_g": 4.0, "fat_g": 5.0, "carbs_g": 8.0},
        "serving_size": "1盘（约180g）",
        "tags": ["low_calorie", "vegetarian", "quick", "low_carb", "high_fiber"],
        "suitable_goal": "lose_fat",
    },
    {
        "name": "金针菇紫菜蛋花汤",
        "category": "soup",
        "meal_type": "dinner",
        "cooking_method": "boil",
        "prep_time_min": 5,
        "cook_time_min": 8,
        "difficulty": "easy",
        "ingredients": [
            {"name": "金针菇", "amount_g": 100},
            {"name": "紫菜", "amount_g": 5},
            {"name": "鸡蛋", "amount_g": 50},
            {"name": "虾皮", "amount_g": 3},
            {"name": "水", "amount_g": 600},
        ],
        "steps": [
            "金针菇去根洗净撕散，紫菜撕小片。",
            "锅中加水烧开，放入金针菇煮 2 分钟。",
            "加入紫菜和虾皮再煮 1 分钟。",
            "鸡蛋打散，沿锅边缓缓淋入成蛋花。",
            "加盐和少许芝麻油调味，撒葱花出锅。",
        ],
        "nutrition_per_serving": {"calories": 110, "protein_g": 10.0, "fat_g": 4.0, "carbs_g": 8.0},
        "serving_size": "1大碗（约350g）",
        "tags": ["low_calorie", "low_fat", "quick", "easy_digest"],
        "suitable_goal": "lose_fat",
    },
    {
        "name": "三文鱼牛油果沙拉",
        "category": "salad",
        "meal_type": "dinner",
        "cooking_method": "raw",
        "prep_time_min": 10,
        "cook_time_min": 8,
        "difficulty": "easy",
        "ingredients": [
            {"name": "三文鱼", "amount_g": 120},
            {"name": "牛油果", "amount_g": 80},
            {"name": "生菜", "amount_g": 60},
            {"name": "小番茄", "amount_g": 50},
            {"name": "柠檬汁", "amount_g": 5},
            {"name": "橄榄油", "amount_g": 5},
        ],
        "steps": [
            "三文鱼用厨房纸吸干水分，加盐和黑胡椒腌制 5 分钟。",
            "平底锅薄油中火，三文鱼每面煎 3-4 分钟（视厚度而定）。",
            "煎好的三文鱼放凉后切成块或用手掰成块。",
            "牛油果去皮去核切块，小番茄对半切，生菜撕小片。",
            "所有食材放入沙拉碗，挤入柠檬汁和橄榄油。",
            "撒少许海盐和黑胡椒，轻轻拌匀即可。",
        ],
        "nutrition_per_serving": {"calories": 380, "protein_g": 28.0, "fat_g": 24.0, "carbs_g": 10.0},
        "serving_size": "1碗（约280g）",
        "tags": ["high_protein", "low_carb", "high_fiber"],
        "suitable_goal": "lose_fat",
    },
    {
        "name": "芦笋炒虾仁",
        "category": "chinese",
        "meal_type": "dinner",
        "cooking_method": "stir_fry",
        "prep_time_min": 10,
        "cook_time_min": 6,
        "difficulty": "easy",
        "ingredients": [
            {"name": "虾仁", "amount_g": 150},
            {"name": "芦笋", "amount_g": 200},
            {"name": "大蒜", "amount_g": 5},
            {"name": "花生油", "amount_g": 8},
        ],
        "steps": [
            "虾仁开背去虾线，加料酒、盐腌制 10 分钟。",
            "芦笋去掉老根，削去根部硬皮，切段。",
            "锅中烧水，芦笋焯水 1 分钟捞出过凉水。",
            "热锅少油，蒜片爆香，虾仁下锅滑炒至变色。",
            "加入芦笋大火翻炒 1 分钟。",
            "加盐和少许蚝油调味，勾薄芡出锅。",
        ],
        "nutrition_per_serving": {"calories": 240, "protein_g": 30.0, "fat_g": 8.0, "carbs_g": 10.0},
        "serving_size": "1盘（约280g）",
        "tags": ["high_protein", "low_fat", "low_carb", "quick"],
        "suitable_goal": "lose_fat",
    },
    {
        "name": "蒜蓉西兰花",
        "category": "chinese",
        "meal_type": "dinner",
        "cooking_method": "stir_fry",
        "prep_time_min": 5,
        "cook_time_min": 5,
        "difficulty": "easy",
        "ingredients": [
            {"name": "西兰花", "amount_g": 250},
            {"name": "大蒜", "amount_g": 10},
            {"name": "花生油", "amount_g": 6},
        ],
        "steps": [
            "西兰花掰成小朵，淡盐水浸泡 10 分钟后洗净。",
            "沸水加盐和几滴油，西兰花焯水 1 分半捞出。",
            "大蒜剁成蒜蓉。热锅少油，小火煸至微黄出香。",
            "转大火下西兰花快速翻炒 30 秒。",
            "加盐和少许蚝油调味，炒匀出锅。",
        ],
        "nutrition_per_serving": {"calories": 100, "protein_g": 5.0, "fat_g": 5.0, "carbs_g": 10.0},
        "serving_size": "1盘（约200g）",
        "tags": ["low_calorie", "vegetarian", "quick", "low_carb", "high_fiber"],
        "suitable_goal": "lose_fat",
    },
    {
        "name": "洋葱炒蛋",
        "category": "chinese",
        "meal_type": "dinner",
        "cooking_method": "stir_fry",
        "prep_time_min": 5,
        "cook_time_min": 6,
        "difficulty": "easy",
        "ingredients": [
            {"name": "鸡蛋", "amount_g": 150},
            {"name": "洋葱", "amount_g": 100},
            {"name": "花生油", "amount_g": 10},
        ],
        "steps": [
            "鸡蛋打散加少许盐搅匀，洋葱切丝。",
            "热锅倒油，油温六成倒入蛋液。",
            "蛋液凝固时用筷子快速划散成大块，盛出备用。",
            "锅中底油下洋葱丝，中火翻炒至半透明出甜味。",
            "倒回鸡蛋块，加盐和少许生抽翻炒均匀出锅。",
        ],
        "nutrition_per_serving": {"calories": 280, "protein_g": 18.0, "fat_g": 18.0, "carbs_g": 10.0},
        "serving_size": "1盘（约230g）",
        "tags": ["quick", "high_protein", "low_carb", "budget_friendly"],
        "suitable_goal": "all",
    },
    {
        "name": "鲫鱼豆腐汤",
        "category": "soup",
        "meal_type": "dinner",
        "cooking_method": "boil",
        "prep_time_min": 15,
        "cook_time_min": 25,
        "difficulty": "medium",
        "ingredients": [
            {"name": "鲫鱼", "amount_g": 300},
            {"name": "豆腐", "amount_g": 200},
            {"name": "生姜", "amount_g": 10},
            {"name": "葱", "amount_g": 10},
            {"name": "花生油", "amount_g": 10},
        ],
        "steps": [
            "鲫鱼去鳞去腮去内脏，洗净后擦干水分。",
            "热锅倒油，油热后放姜片，放入鱼中小火两面煎至微黄。",
            "倒入足量开水（汤才会白），大火烧开后撇去浮沫。",
            "放入葱段，转中火煮 10 分钟至汤色乳白。",
            "豆腐切块入锅，继续煮 5 分钟。",
            "加盐和白胡椒粉调味，撒葱花出锅。",
        ],
        "nutrition_per_serving": {"calories": 340, "protein_g": 35.0, "fat_g": 16.0, "carbs_g": 6.0},
        "serving_size": "1大碗（约450g）",
        "tags": ["high_protein", "comfort_food", "easy_digest"],
        "suitable_goal": "build_muscle",
    },
    {
        "name": "凉拌木耳",
        "category": "chinese",
        "meal_type": "dinner",
        "cooking_method": "boil",
        "prep_time_min": 30,
        "cook_time_min": 5,
        "difficulty": "easy",
        "ingredients": [
            {"name": "黑木耳", "amount_g": 20},
            {"name": "黄瓜", "amount_g": 80},
            {"name": "大蒜", "amount_g": 8},
            {"name": "醋", "amount_g": 10},
            {"name": "生抽", "amount_g": 8},
            {"name": "芝麻油", "amount_g": 3},
        ],
        "steps": [
            "干木耳提前温水泡发（约 30 分钟），去蒂洗净。",
            "泡发的木耳撕成小朵，沸水焯烫 3 分钟捞出过凉水。",
            "黄瓜拍裂切段。",
            "调拌汁：蒜蓉、生抽、醋、盐、糖、芝麻油搅匀。",
            "木耳和黄瓜放入碗中，倒入拌汁拌匀即可。",
        ],
        "nutrition_per_serving": {"calories": 80, "protein_g": 3.0, "fat_g": 3.0, "carbs_g": 12.0},
        "serving_size": "1盘（约200g）",
        "tags": ["low_calorie", "vegetarian", "high_fiber"],
        "suitable_goal": "lose_fat",
    },

    # ── 加餐/沙拉 (10) ─────────────────────────────────────────
    {
        "name": "鸡胸肉沙拉",
        "category": "salad",
        "meal_type": "snack",
        "cooking_method": "raw",
        "prep_time_min": 15,
        "cook_time_min": 10,
        "difficulty": "easy",
        "ingredients": [
            {"name": "鸡胸肉", "amount_g": 100},
            {"name": "生菜", "amount_g": 60},
            {"name": "小番茄", "amount_g": 60},
            {"name": "黄瓜", "amount_g": 50},
            {"name": "玉米粒", "amount_g": 30},
            {"name": "橄榄油", "amount_g": 5},
        ],
        "steps": [
            "鸡胸肉加盐和黑胡椒腌制 10 分钟。",
            "平底锅中火，每面煎 4-5 分钟至熟透，切片备用。",
            "生菜洗净撕碎铺底，黄瓜切片，小番茄对半切。",
            "玉米粒焯水 1 分钟捞出。",
            "所有食材摆入沙拉碗，淋少量橄榄油和柠檬汁。",
            "撒少许海盐和黑胡椒即可。",
        ],
        "nutrition_per_serving": {"calories": 220, "protein_g": 28.0, "fat_g": 8.0, "carbs_g": 12.0},
        "serving_size": "1碗（约280g）",
        "tags": ["high_protein", "low_fat", "low_carb", "meal_prep"],
        "suitable_goal": "lose_fat",
    },
    {
        "name": "牛油果鸡蛋沙拉",
        "category": "salad",
        "meal_type": "snack",
        "cooking_method": "raw",
        "prep_time_min": 10,
        "cook_time_min": 8,
        "difficulty": "easy",
        "ingredients": [
            {"name": "牛油果", "amount_g": 80},
            {"name": "鸡蛋", "amount_g": 100},
            {"name": "小番茄", "amount_g": 50},
            {"name": "生菜", "amount_g": 40},
            {"name": "柠檬汁", "amount_g": 5},
        ],
        "steps": [
            "鸡蛋冷水下锅，水开煮 8 分钟，过凉水剥壳切块。",
            "牛油果对半切开去核，挖出果肉切块。",
            "小番茄对半切，生菜撕小块。",
            "所有食材放入沙拉碗。",
            "挤入新鲜柠檬汁，撒盐和黑胡椒，轻轻拌匀即可。",
        ],
        "nutrition_per_serving": {"calories": 320, "protein_g": 16.0, "fat_g": 24.0, "carbs_g": 10.0},
        "serving_size": "1碗（约250g）",
        "tags": ["high_protein", "low_carb", "keto_friendly"],
        "suitable_goal": "build_muscle",
    },
    {
        "name": "酸奶水果杯",
        "category": "western",
        "meal_type": "snack",
        "cooking_method": "raw",
        "prep_time_min": 5,
        "cook_time_min": 0,
        "difficulty": "easy",
        "ingredients": [
            {"name": "酸奶", "amount_g": 200},
            {"name": "蓝莓", "amount_g": 50},
            {"name": "香蕉", "amount_g": 80},
            {"name": "燕麦片", "amount_g": 15},
        ],
        "steps": [
            "香蕉切片，蓝莓洗净沥干。",
            "杯中先铺一层酸奶，再铺一层燕麦片。",
            "放入一层香蕉片和蓝莓。",
            "重复以上步骤至杯子八分满。",
            "顶部用水果装饰，即可食用。",
        ],
        "nutrition_per_serving": {"calories": 280, "protein_g": 10.0, "fat_g": 8.0, "carbs_g": 42.0},
        "serving_size": "1杯（约300g）",
        "tags": ["quick", "high_fiber", "vegetarian"],
        "suitable_goal": "all",
    },
    {
        "name": "烤红薯",
        "category": "chinese",
        "meal_type": "snack",
        "cooking_method": "bake",
        "prep_time_min": 5,
        "cook_time_min": 40,
        "difficulty": "easy",
        "ingredients": [
            {"name": "红薯", "amount_g": 300},
        ],
        "steps": [
            "红薯洗净擦干，选择细长形状的更容易烤熟。",
            "烤箱预热 200℃。",
            "烤盘铺锡纸，红薯放上，中层烤 35-40 分钟。",
            "中途翻面一次，至红薯表面流蜜、用筷子轻松扎透即可。",
            "空气炸锅：200℃ 烤 25-30 分钟（视大小调整）。",
        ],
        "nutrition_per_serving": {"calories": 260, "protein_g": 5.0, "fat_g": 0.3, "carbs_g": 60.0},
        "serving_size": "1个（约300g）",
        "tags": ["vegetarian", "low_fat", "high_fiber"],
        "suitable_goal": "lose_fat",
    },
    {
        "name": "凉拌鸡丝",
        "category": "chinese",
        "meal_type": "snack",
        "cooking_method": "boil",
        "prep_time_min": 10,
        "cook_time_min": 15,
        "difficulty": "easy",
        "ingredients": [
            {"name": "鸡胸肉", "amount_g": 150},
            {"name": "黄瓜", "amount_g": 80},
            {"name": "胡萝卜", "amount_g": 50},
            {"name": "大蒜", "amount_g": 5},
            {"name": "生抽", "amount_g": 10},
            {"name": "醋", "amount_g": 8},
            {"name": "芝麻油", "amount_g": 3},
        ],
        "steps": [
            "鸡胸肉冷水下锅，加姜片和料酒，水开后煮 12 分钟至熟透。",
            "捞出放凉，用刀背拍松后手撕成细丝。",
            "黄瓜和胡萝卜切细丝。大蒜剁成蒜蓉。",
            "调拌汁：蒜蓉、生抽、醋、少许糖、芝麻油、辣椒油（可选）搅匀。",
            "将鸡丝、黄瓜丝、胡萝卜丝放入大碗，倒入拌汁拌匀。",
            "装盘后撒白芝麻即可。",
        ],
        "nutrition_per_serving": {"calories": 210, "protein_g": 32.0, "fat_g": 6.0, "carbs_g": 8.0},
        "serving_size": "1盘（约220g）",
        "tags": ["high_protein", "low_fat", "low_carb", "meal_prep"],
        "suitable_goal": "lose_fat",
    },
    {
        "name": "五香毛豆",
        "category": "chinese",
        "meal_type": "snack",
        "cooking_method": "boil",
        "prep_time_min": 10,
        "cook_time_min": 15,
        "difficulty": "easy",
        "ingredients": [
            {"name": "毛豆", "amount_g": 300},
            {"name": "花椒", "amount_g": 2},
            {"name": "盐", "amount_g": 8},
            {"name": "水", "amount_g": 1000},
        ],
        "steps": [
            "毛豆洗净，用剪刀剪去两端小角方便入味。",
            "锅中加水，放入花椒、盐和毛豆。",
            "大火烧开后转中火煮 12-15 分钟。",
            "关火后让毛豆在卤水中浸泡 15 分钟更入味。",
            "捞出沥干装盘即可，冷热皆宜。",
        ],
        "nutrition_per_serving": {"calories": 180, "protein_g": 14.0, "fat_g": 6.0, "carbs_g": 18.0},
        "serving_size": "1盘（约250g）",
        "tags": ["vegetarian", "high_protein", "high_fiber", "meal_prep"],
        "suitable_goal": "all",
    },
    {
        "name": "蒸玉米",
        "category": "chinese",
        "meal_type": "snack",
        "cooking_method": "steam",
        "prep_time_min": 2,
        "cook_time_min": 15,
        "difficulty": "easy",
        "ingredients": [
            {"name": "玉米", "amount_g": 250},
        ],
        "steps": [
            "玉米剥去外层老叶，保留内层 1-2 层嫩皮。",
            "蒸锅水开后放入玉米。",
            "大火蒸 12-15 分钟至熟透。",
            "取出后可刷少许黄油或直接食用。",
        ],
        "nutrition_per_serving": {"calories": 200, "protein_g": 7.0, "fat_g": 2.5, "carbs_g": 42.0},
        "serving_size": "1根（约250g）",
        "tags": ["vegetarian", "low_fat", "high_fiber", "quick"],
        "suitable_goal": "all",
    },
    {
        "name": "鹰嘴豆泥配蔬菜条",
        "category": "western",
        "meal_type": "snack",
        "cooking_method": "raw",
        "prep_time_min": 10,
        "cook_time_min": 0,
        "difficulty": "easy",
        "ingredients": [
            {"name": "鹰嘴豆", "amount_g": 120},
            {"name": "橄榄油", "amount_g": 8},
            {"name": "柠檬汁", "amount_g": 5},
            {"name": "黄瓜", "amount_g": 60},
            {"name": "胡萝卜", "amount_g": 60},
            {"name": "芹菜", "amount_g": 40},
        ],
        "steps": [
            "罐装鹰嘴豆沥水冲洗（干豆则需提前泡发煮熟）。",
            "鹰嘴豆放入料理机，加橄榄油、柠檬汁、少许盐和水。",
            "搅打成顺滑的豆泥，太干可加水调整稠度。",
            "黄瓜、胡萝卜、芹菜切手指粗细的条。",
            "豆泥盛入碗中淋少许橄榄油，搭配蔬菜条一同食用。",
        ],
        "nutrition_per_serving": {"calories": 300, "protein_g": 13.0, "fat_g": 12.0, "carbs_g": 36.0},
        "serving_size": "1份",
        "tags": ["vegetarian", "high_fiber", "meal_prep"],
        "suitable_goal": "maintain",
    },
    {
        "name": "山药排骨汤",
        "category": "soup",
        "meal_type": "snack",
        "cooking_method": "boil",
        "prep_time_min": 15,
        "cook_time_min": 50,
        "difficulty": "easy",
        "ingredients": [
            {"name": "猪排骨", "amount_g": 150},
            {"name": "山药", "amount_g": 200},
            {"name": "胡萝卜", "amount_g": 80},
            {"name": "生姜", "amount_g": 8},
        ],
        "steps": [
            "排骨冷水下锅焯水去血沫，捞出洗净。",
            "山药去皮切滚刀块（戴手套防止手痒），胡萝卜去皮切块。",
            "排骨和姜片放入汤锅，加足量水大火烧开。",
            "转小火炖 30 分钟至排骨软烂。",
            "加入胡萝卜和山药继续炖 15 分钟。",
            "加盐调味出锅，撒葱花即可。",
        ],
        "nutrition_per_serving": {"calories": 350, "protein_g": 22.0, "fat_g": 15.0, "carbs_g": 30.0},
        "serving_size": "1大碗（约400g）",
        "tags": ["comfort_food", "easy_digest"],
        "suitable_goal": "all",
    },
    {
        "name": "凯撒沙拉",
        "category": "salad",
        "meal_type": "snack",
        "cooking_method": "raw",
        "prep_time_min": 10,
        "cook_time_min": 8,
        "difficulty": "easy",
        "ingredients": [
            {"name": "生菜", "amount_g": 100},
            {"name": "鸡胸肉", "amount_g": 80},
            {"name": "全麦面包", "amount_g": 30},
            {"name": "鸡蛋", "amount_g": 50},
            {"name": "橄榄油", "amount_g": 8},
            {"name": "柠檬汁", "amount_g": 5},
        ],
        "steps": [
            "鸡胸肉加盐和黑胡椒腌制后煎熟，切片。",
            "全麦面包切小丁，平底锅小火烘干成面包丁（或烤箱 150℃ 烤 8 分钟）。",
            "鸡蛋煮 8 分钟，过凉水剥壳切成四份。",
            "生菜洗净撕大片铺底。",
            "铺上鸡胸肉片、面包丁和鸡蛋块。",
            "用橄榄油、柠檬汁、少许盐和黑胡椒拌匀作为酱汁淋上即可。",
        ],
        "nutrition_per_serving": {"calories": 310, "protein_g": 28.0, "fat_g": 14.0, "carbs_g": 16.0},
        "serving_size": "1碗（约280g）",
        "tags": ["high_protein", "low_carb"],
        "suitable_goal": "lose_fat",
    },
]


# ═══════════════════════════════════════════════════════════════════
# 主流程
# ═══════════════════════════════════════════════════════════════════


async def seed() -> int:
    """插入缺失的菜谱，返回新增数量。"""
    logger.info("数据库地址: %s", settings.database_url)
    inserted = 0

    async with async_session() as db:
        for recipe_data in RECIPES:
            # 按名称查重
            stmt = select(Recipe).where(Recipe.name == recipe_data["name"])
            result = await db.execute(stmt)
            existing = result.scalar_one_or_none()
            if existing:
                logger.info("  跳过（已存在）: %s", recipe_data["name"])
                continue

            recipe = Recipe(
                id=uuid.uuid4(),
                name=recipe_data["name"],
                category=recipe_data.get("category"),
                meal_type=recipe_data.get("meal_type"),
                cooking_method=recipe_data.get("cooking_method"),
                prep_time_min=recipe_data.get("prep_time_min"),
                cook_time_min=recipe_data.get("cook_time_min"),
                difficulty=recipe_data.get("difficulty"),
                ingredients=recipe_data["ingredients"],
                steps=recipe_data["steps"],
                nutrition_per_serving=recipe_data["nutrition_per_serving"],
                serving_size=recipe_data.get("serving_size"),
                tags=recipe_data.get("tags", []),
                suitable_goal=recipe_data.get("suitable_goal"),
            )
            db.add(recipe)
            inserted += 1
            logger.info("  已插入: %s", recipe_data["name"])

        if inserted > 0:
            await db.commit()
            logger.info("提交 %d 条新菜谱", inserted)
        else:
            logger.info("所有菜谱已存在，无需插入")

    return inserted


def main() -> None:
    count = asyncio.run(seed())
    logger.info("完成！共新增 %d 道菜谱", count)
    # 验证总数
    async def verify():
        async with async_session() as db:
            result = await db.execute(select(Recipe))
            total = len(result.scalars().all())
            logger.info("数据库中食谱总数: %d", total)
    asyncio.run(verify())


if __name__ == "__main__":
    main()
